<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>知识库 | 知识库</title><meta name="author" content="Asuka"><meta name="copyright" content="Asuka"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="在 Python 中，所有异常必须为一个派生自 BaseException 的类的实例。 在带有提及一个特定类的 except 子句的 try 语句中，该子句也会处理任何派生自该类的异常类（但不处理 它 所派生出的异常类）。 通过子类化创建的两个不相关异常类永远是不等效的，既使它们具有相同的名称。 下面列出的内置异常可通过解释器或内置函数来生成。除非另有说明，它们都会具有一个提示导致错误详细原因的">
<meta property="og:type" content="article">
<meta property="og:title" content="知识库">
<meta property="og:url" content="http://asuka23333.github.io/2024/01/08/Python/%E5%86%85%E7%BD%AE%E5%BC%82%E5%B8%B8/index.html">
<meta property="og:site_name" content="知识库">
<meta property="og:description" content="在 Python 中，所有异常必须为一个派生自 BaseException 的类的实例。 在带有提及一个特定类的 except 子句的 try 语句中，该子句也会处理任何派生自该类的异常类（但不处理 它 所派生出的异常类）。 通过子类化创建的两个不相关异常类永远是不等效的，既使它们具有相同的名称。 下面列出的内置异常可通过解释器或内置函数来生成。除非另有说明，它们都会具有一个提示导致错误详细原因的">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="http://asuka23333.github.io/img/net_icon.png">
<meta property="article:published_time" content="2024-01-08T07:01:50.204Z">
<meta property="article:modified_time" content="2023-12-29T14:02:15.511Z">
<meta property="article:author" content="Asuka">
<meta property="article:tag" content="Python Python标准库 异常上下文 从内置异常继承 基类 具体异常 警告 异常层次结构">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="http://asuka23333.github.io/img/net_icon.png"><link rel="shortcut icon" href="/img/net_icon.png"><link rel="canonical" href="http://asuka23333.github.io/2024/01/08/Python/%E5%86%85%E7%BD%AE%E5%BC%82%E5%B8%B8/index.html"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css?v=4.12.0"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.1/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.32/dist/fancybox/fancybox.min.css" media="print" onload="this.media='all'"><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":-1,"unescape":true,"languages":{"hits_empty":"找不到您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  noticeOutdate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false},
  copy: {
    success: '复制成功',
    error: '复制错误',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: undefined,
  lightbox: 'fancybox',
  Snackbar: undefined,
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid@4.11.0/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: false,
  percent: {
    toc: true,
    rightside: false,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '知识库',
  isPost: true,
  isHome: false,
  isHighlightShrink: true,
  isToc: true,
  postUpdate: '2023-12-29 22:02:15'
}</script><script>(win=>{
      win.saveToLocal = {
        set: (key, value, ttl) => {
          if (ttl === 0) return
          const now = Date.now()
          const expiry = now + ttl * 86400000
          const item = {
            value,
            expiry
          }
          localStorage.setItem(key, JSON.stringify(item))
        },
      
        get: key => {
          const itemStr = localStorage.getItem(key)
      
          if (!itemStr) {
            return undefined
          }
          const item = JSON.parse(itemStr)
          const now = Date.now()
      
          if (now > item.expiry) {
            localStorage.removeItem(key)
            return undefined
          }
          return item.value
        }
      }
    
      win.getScript = (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        script.onerror = reject
        script.onload = script.onreadystatechange = function() {
          const loadState = this.readyState
          if (loadState && loadState !== 'loaded' && loadState !== 'complete') return
          script.onload = script.onreadystatechange = null
          resolve()
        }

        Object.keys(attr).forEach(key => {
          script.setAttribute(key, attr[key])
        })

        document.head.appendChild(script)
      })
    
      win.getCSS = (url, id = false) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onerror = reject
        link.onload = link.onreadystatechange = function() {
          const loadState = this.readyState
          if (loadState && loadState !== 'loaded' && loadState !== 'complete') return
          link.onload = link.onreadystatechange = null
          resolve()
        }
        document.head.appendChild(link)
      })
    
      win.activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      win.activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }
      const t = saveToLocal.get('theme')
    
        if (t === 'dark') activateDarkMode()
        else if (t === 'light') activateLightMode()
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        if (asideStatus === 'hide') {
          document.documentElement.classList.add('hide-aside')
        } else {
          document.documentElement.classList.remove('hide-aside')
        }
      }
    
      const detectApple = () => {
        if(/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)){
          document.documentElement.classList.add('apple')
        }
      }
      detectApple()
    })(window)</script><meta name="generator" content="Hexo 7.0.0"></head><body><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img is-center"><img src="/img/net_icon.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="sidebar-site-data site-data is-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">41</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">39</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">0</div></a></div><hr class="custom-hr"/><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> 主页</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> 标签</span></a></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-language"></i><span> 语言</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/en/"><span> 英语</span></a></li><li><a class="site-page child" href="/ja/"><span> 日语</span></a></li></ul></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-shopping-cart"></i><span> 电商</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/amazon/"><i class="fa-fw fas fa-shopping-cart"></i><span> 亚马逊</span></a></li><li><a class="site-page child" href="/rakuten/"><i class="fa-fw fas fa-shopping-cart"></i><span> 乐天</span></a></li><li><a class="site-page child" href="/yahoo/"><i class="fa-fw fas fa-shopping-cart"></i><span> 雅虎</span></a></li></ul></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-folder-open"></i><span> 编程</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/Python/"><span> Python</span></a></li><li><a class="site-page child" href="/Java/"><span> Java</span></a></li><li><a class="site-page child" href="/CMD/"><span> CMD</span></a></li><li><a class="site-page child" href="/CSharp/"><span> C#</span></a></li><li><a class="site-page child" href="/HTML/"><span> HTML</span></a></li><li><a class="site-page child" href="/CSS/"><span> CSS</span></a></li><li><a class="site-page child" href="/JavaScript/"><span> JavaScript</span></a></li></ul></div><div class="menus_item"><a class="site-page" href="/link/"><i class="fa-fw fas fa-link"></i><span> 收藏链接</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg" id="page-header"><nav id="nav"><span id="blog-info"><a href="/" title="知识库"><span class="site-name">知识库</span></a></span><div id="menus"><div id="search-button"><a class="site-page social-icon search" href="javascript:void(0);"><i class="fas fa-search fa-fw"></i><span> 搜索</span></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> 主页</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> 标签</span></a></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-language"></i><span> 语言</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/en/"><span> 英语</span></a></li><li><a class="site-page child" href="/ja/"><span> 日语</span></a></li></ul></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-shopping-cart"></i><span> 电商</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/amazon/"><i class="fa-fw fas fa-shopping-cart"></i><span> 亚马逊</span></a></li><li><a class="site-page child" href="/rakuten/"><i class="fa-fw fas fa-shopping-cart"></i><span> 乐天</span></a></li><li><a class="site-page child" href="/yahoo/"><i class="fa-fw fas fa-shopping-cart"></i><span> 雅虎</span></a></li></ul></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-folder-open"></i><span> 编程</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" href="/Python/"><span> Python</span></a></li><li><a class="site-page child" href="/Java/"><span> Java</span></a></li><li><a class="site-page child" href="/CMD/"><span> CMD</span></a></li><li><a class="site-page child" href="/CSharp/"><span> C#</span></a></li><li><a class="site-page child" href="/HTML/"><span> HTML</span></a></li><li><a class="site-page child" href="/CSS/"><span> CSS</span></a></li><li><a class="site-page child" href="/JavaScript/"><span> JavaScript</span></a></li></ul></div><div class="menus_item"><a class="site-page" href="/link/"><i class="fa-fw fas fa-link"></i><span> 收藏链接</span></a></div></div><div id="toggle-menu"><a class="site-page" href="javascript:void(0);"><i class="fas fa-bars fa-fw"></i></a></div></div></nav><div id="post-info"><h1 class="post-title">无题</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-01-08T07:01:50.204Z" title="发表于 2024-01-08 15:01:50">2024-01-08</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2023-12-29T14:02:15.511Z" title="更新于 2023-12-29 22:02:15">2023-12-29</time></span></div><div class="meta-secondline"></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="post-content" id="article-container"><p>在 Python 中，所有异常必须为一个派生自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException" title="BaseException"><code>BaseException</code></a> 的类的实例。 在带有提及一个特定类的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#except"><code>except</code></a> 子句的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#try"><code>try</code></a> 语句中，该子句也会处理任何派生自该类的异常类（但不处理 <em>它</em> 所派生出的异常类）。 通过子类化创建的两个不相关异常类永远是不等效的，既使它们具有相同的名称。</p>
<p>下面列出的内置异常可通过解释器或内置函数来生成。除非另有说明，它们都会具有一个提示导致错误详细原因的“关联值”。 这可以是一个字符串或由多个信息项（例如一个错误码和一个解释错误的字符串）组成的元组。 关联值通常会作为参数被传递给异常类的构造器。</p>
<p>用户代码可以引发内置异常。 这可被用于测试异常处理程序或报告错误条件，“就像” 在解释器引发了相同异常的情况时一样；但是请注意，没有任何机制能防止用户代码引发不适当的错误。</p>
<p>内置异常类可以被子类化以定义新的异常；鼓励程序员从 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="Exception"><code>Exception</code></a> 类或它的某个子类而不是从 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException" title="BaseException"><code>BaseException</code></a> 来派生新的异常。 关于定义异常的更多信息可以在 Python 教程的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/tutorial/errors.html#tut-userexceptions">用户自定义异常</a> 部分查看。</p>
<h2 id="异常上下文"><a href="#异常上下文" class="headerlink" title="异常上下文"></a>异常上下文</h2><p>当有其他异常已经被处理的情况下又引发一个新异常的时候，新异常的 <code>__context__</code> 属性会被自动设为已经被处理的异常。 异常可以在使用了 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#except"><code>except</code></a> 或 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#finally"><code>finally</code></a> 子句，或者 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#with"><code>with</code></a> 语句的时候被处理。</p>
<p>这个隐式异常上下文可以通过使用 <code>from</code> 配合 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/simple_stmts.html#raise"><code>raise</code></a> 来补充一个显式的原因:</p>
<p>raise new_exc from original_exc</p>
<p>跟在 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/simple_stmts.html#raise"><code>from</code></a> 之后一表达式必须为一个异常或 <code>None</code>。 它将在所引发的异常上被设置为 <code>__cause__</code>。 设置 <code>__cause__</code> 还会隐式地将 <code>__suppress_context__</code> 属性设为 <code>True</code>，这样使用 <code>raise new_exc from None</code> 可以有效地将旧异常替换为新异常来显示其目的 (例如将 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#KeyError" title="KeyError"><code>KeyError</code></a> 转换为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#AttributeError" title="AttributeError"><code>AttributeError</code></a>)，同时让旧异常在 <code>__context__</code> 中保持可用状态以便在调试时进行内省。</p>
<p>除了异常本身的回溯以外，默认的回溯还会显示这些串连的异常。 <code>__cause__</code> 中的显式串连异常如果存在将总是显示。 <code>__context__</code> 中的隐式串连异常仅在 <code>__cause__</code> 为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/constants.html#None" title="None"><code>None</code></a> 并且 <code>__suppress_context__</code> 为假值时显示。</p>
<p>不论在哪种情况下，异常本身总会在任何串连异常之后显示，以便回溯的最后一行总是显示所引发的最后一个异常。</p>
<h2 id="从内置异常继承"><a href="#从内置异常继承" class="headerlink" title="从内置异常继承"></a>从内置异常继承</h2><p>用户代码可以创建继承自某个异常类型的子类。 建议每次仅子类化一个异常类型以避免多个基类处理 <code>args</code> 属性的不同方式，以及内存布局不兼容可能导致的冲突。</p>
<p><strong>CPython 实现细节：</strong> 大多数内置异常都用 C 实现以保证运行效率，参见: <a target="_blank" rel="noopener" href="https://github.com/python/cpython/tree/3.10/Objects/exceptions.c">Objects&#x2F;exceptions.c</a>。 其中一些具有自定义内存布局，这使得创建继承自多个异常类型的子类成为不可能。 一个类型的内存布局属于实现细节并可能随着 Python 版本升级而改变，导致在未来可能产生新的冲突。 因此，建议完全避免子类化多个异常类型。</p>
<h2 id="基类"><a href="#基类" class="headerlink" title="基类"></a>基类</h2><p>下列异常主要被用作其他异常的基类。</p>
<p><em>exception</em> <code>BaseException</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException" title="永久链接至目标"></a></p>
<p>所有内置异常的基类。 它不应该被用户自定义类直接继承 (这种情况请使用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="Exception"><code>Exception</code></a>)。 如果在此类的实例上调用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/stdtypes.html#str" title="str"><code>str()</code></a>，则会返回实例的参数表示，或者当没有参数时返回空字符串。</p>
<p><code>args</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException.args" title="永久链接至目标"></a></p>
<p>传给异常构造器的参数元组。 某些内置异常 (例如 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a>) 接受特定数量的参数并赋予此元组中的元素特殊的含义，而其他异常通常只接受一个给出错误信息的单独字符串。</p>
<p><code>with_traceback</code>(<em>tb</em>)<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException.with_traceback" title="永久链接至目标"></a></p>
<p>此方法会将 <em>tb</em> 设为新的异常回溯信息并返回异常对象。 它在 <a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a> 的异常链特性可用之前更为常用。 下面的例子演示了我们如何将一个 <code>SomeException</code> 实例转换为 <code>OtherException</code> 实例而保留回溯信息。 异常一旦被引发，当前帧会被推至 <code>OtherException</code> 的回溯栈顶端，就像当我们允许原始 <code>SomeException</code> 被传播给调用方时它的回溯栈将会发生的情形一样。:</p>
<p>try:<br>    …<br>except SomeException:<br>    tb &#x3D; sys.exc_info()[2]<br>    raise OtherException(…).with_traceback(tb)</p>
<p><em>exception</em> <code>Exception</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="永久链接至目标"></a></p>
<p>所有内置的非系统退出类异常都派生自此类。 所有用户自定义异常也应当派生自此类。</p>
<p><em>exception</em> <code>ArithmeticError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ArithmeticError" title="永久链接至目标"></a></p>
<p>此基类用于派生针对各种算术类错误而引发的内置异常: <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OverflowError" title="OverflowError"><code>OverflowError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ZeroDivisionError" title="ZeroDivisionError"><code>ZeroDivisionError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#FloatingPointError" title="FloatingPointError"><code>FloatingPointError</code></a>。</p>
<p><em>exception</em> <code>BufferError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BufferError" title="永久链接至目标"></a></p>
<p>当与 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/c-api/buffer.html#bufferobjects">缓冲区</a> 相关的操作无法执行时将被引发。</p>
<p><em>exception</em> <code>LookupError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#LookupError" title="永久链接至目标"></a></p>
<p>此基类用于派生当映射或序列所使用的键或索引无效时引发的异常: <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IndexError" title="IndexError"><code>IndexError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#KeyError" title="KeyError"><code>KeyError</code></a>。 这可以通过 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/codecs.html#codecs.lookup" title="codecs.lookup"><code>codecs.lookup()</code></a> 来直接引发。</p>
<h2 id="具体异常"><a href="#具体异常" class="headerlink" title="具体异常"></a>具体异常</h2><p>以下异常属于经常被引发的异常。</p>
<p><em>exception</em> <code>AssertionError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#AssertionError" title="永久链接至目标"></a></p>
<p>当 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/simple_stmts.html#assert"><code>assert</code></a> 语句失败时将被引发。</p>
<p><em>exception</em> <code>AttributeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#AttributeError" title="永久链接至目标"></a></p>
<p>当属性引用 (参见 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/expressions.html#attribute-references">属性引用</a>) 或赋值失败时将被引发。 （当一个对象根本不支持属性引用或属性赋值时则将引发 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#TypeError" title="TypeError"><code>TypeError</code></a>。）</p>
<p><code>name</code> 和 <code>obj</code> 属性可以使用构造器的仅限关键字参数来设置。 它们如果被设置则分别代表要尝试访问的属性名称以及所访问的该属性的对象。</p>
<p>在 3.10 版更改: 增加了 <code>name</code> 和 <code>obj</code> 属性。</p>
<p><em>exception</em> <code>EOFError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#EOFError" title="永久链接至目标"></a></p>
<p>当 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#input" title="input"><code>input()</code></a> 函数未读取任何数据即达到文件结束条件 (EOF) 时将被引发。 （另外，<code>io.IOBase.read()</code> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/io.html#io.IOBase.readline" title="io.IOBase.readline"><code>io.IOBase.readline()</code></a> 方法在遇到 EOF 则将返回一个空字符串。）</p>
<p><em>exception</em> <code>FloatingPointError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#FloatingPointError" title="永久链接至目标"></a></p>
<p>目前未被使用。</p>
<p><em>exception</em> <code>GeneratorExit</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#GeneratorExit" title="永久链接至目标"></a></p>
<p>当一个 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-generator">generator</a> 或 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-coroutine">coroutine</a> 被关闭时将被引发；参见 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/expressions.html#generator.close" title="generator.close"><code>generator.close()</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/datamodel.html#coroutine.close" title="coroutine.close"><code>coroutine.close()</code></a>。 它直接继承自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException" title="BaseException"><code>BaseException</code></a> 而不是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="Exception"><code>Exception</code></a>，因为从技术上来说它并不是一个错误。</p>
<p><em>exception</em> <code>ImportError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ImportError" title="永久链接至目标"></a></p>
<p>当 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/simple_stmts.html#import"><code>import</code></a> 语句尝试加载模块遇到麻烦时将被引发。 并且当 <code>from ... import</code> 中的 “from list” 存在无法找到的名称时也会被引发。</p>
<p><code>name</code> 与 <code>path</code> 属性可通过对构造器使用仅关键字参数来设定。 设定后它们将分别表示被尝试导入的模块名称与触发异常的任意文件所在路径。</p>
<p>在 3.3 版更改: 添加了 <code>name</code> 与 <code>path</code> 属性。</p>
<p><em>exception</em> <code>ModuleNotFoundError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ModuleNotFoundError" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ImportError" title="ImportError"><code>ImportError</code></a> 的子类，当一个模块无法被定位时将由 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/simple_stmts.html#import"><code>import</code></a> 引发。 当在 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/sys.html#sys.modules" title="sys.modules"><code>sys.modules</code></a> 中找到 <code>None</code> 时也会被引发。</p>
<p>3.6 新版功能.</p>
<p><em>exception</em> <code>IndexError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IndexError" title="永久链接至目标"></a></p>
<p>当序列抽取超出范围时将被引发。 （切片索引会被静默截短到允许的范围；如果指定索引不是整数则 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#TypeError" title="TypeError"><code>TypeError</code></a> 会被引发。）</p>
<p><em>exception</em> <code>KeyError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#KeyError" title="永久链接至目标"></a></p>
<p>当在现有键集合中找不到指定的映射（字典）键时将被引发。</p>
<p><em>exception</em> <code>KeyboardInterrupt</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#KeyboardInterrupt" title="永久链接至目标"></a></p>
<p>当用户按下中断键 (通常为 Control-C 或 Delete) 时将被引发。 在执行期间，会定期检测中断信号。 该异常继承自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException" title="BaseException"><code>BaseException</code></a> 以确保不会被处理 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="Exception"><code>Exception</code></a> 的代码意外捕获，这样可以避免退出解释器。</p>
<p>注解</p>
<p> </p>
<p>捕获 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#KeyboardInterrupt" title="KeyboardInterrupt"><code>KeyboardInterrupt</code></a> 需要特别考虑。 因为它可能会在不可预知的点位被引发，在某些情况下，它可能使运行中的程序陷入不一致的状态。 通常最好是让 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#KeyboardInterrupt" title="KeyboardInterrupt"><code>KeyboardInterrupt</code></a> 尽快结束程序或者完全避免引发它。 (参见 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/signal.html#handlers-and-exceptions">有关信号处理句柄和异常的注释</a>。)</p>
<p><em>exception</em> <code>MemoryError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#MemoryError" title="永久链接至目标"></a></p>
<p>当一个操作耗尽内存但情况仍可（通过删除一些对象）进行挽救时将被引发。 关联的值是一个字符串，指明是哪种（内部）操作耗尽了内存。 请注意由于底层的内存管理架构（C 的 <code>malloc()</code> 函数），解释器也许并不总是能够从这种情况下完全恢复；但它毕竟可以引发一个异常，这样就能打印出栈回溯信息，以便找出导致问题的失控程序。</p>
<p><em>exception</em> <code>NameError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#NameError" title="永久链接至目标"></a></p>
<p>当某个局部或全局名称未找到时将被引发。 此异常仅用于非限定名称。 关联的值是一条错误信息，其中包含未找到的名称。</p>
<p><code>name</code> 属性可以使用构造器的仅限关键字参数来设置。 它如果被设置则代表要尝试访问的变量名称。</p>
<p>在 3.10 版更改: 增加了 <code>name</code> 属性。</p>
<p><em>exception</em> <code>NotImplementedError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#NotImplementedError" title="永久链接至目标"></a></p>
<p>此异常派生自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeError" title="RuntimeError"><code>RuntimeError</code></a>。 在用户自定义的基类中，抽象方法应当在其要求所派生类重载该方法，或是在其要求所开发的类提示具体实现尚待添加时引发此异常。</p>
<p>注解</p>
<p> </p>
<p>它不应当用来表示一个运算符或方法根本不能被支持 – 在此情况下应当让特定运算符 &#x2F; 方法保持未定义，或者在子类中将其设为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/constants.html#None" title="None"><code>None</code></a>。</p>
<p>注解</p>
<p> </p>
<p><code>NotImplementedError</code> 和 <code>NotImplemented</code> 不可互换，即使它们有相似的名称和用途。 请参阅 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/constants.html#NotImplemented" title="NotImplemented"><code>NotImplemented</code></a> 了解有关何时使用它们的详细说明。</p>
<p><em>exception</em> <code>OSError</code>([<em>arg</em>])<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="永久链接至目标"></a></p>
<p><em>exception</em> <code>OSError</code>(<em>errno</em>, <em>strerror</em>[, <em>filename</em>[, <em>winerror</em>[, <em>filename2</em>]]])</p>
<p>此异常在一个系统函数返回系统相关的错误时将被引发，此类错误包括 I&#x2F;O 操作失败例如 “文件未找到” 或 “磁盘已满” 等（不包括非法参数类型或其他偶然性错误）。</p>
<p>构造器的第二种形式可设置如下所述的相应属性。 如果未指定这些属性则默认为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/constants.html#None" title="None"><code>None</code></a>。 为了能向下兼容，如果传入了三个参数，则 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException.args" title="BaseException.args"><code>args</code></a> 属性将仅包含由前两个构造器参数组成的 2 元组。</p>
<p>构造器实际返回的往往是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a> 的某个子类，如下文 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#os-exceptions">OS exceptions</a> 中所描述的。 具体的子类取决于最终的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.errno" title="OSError.errno"><code>errno</code></a> 值。 此行为仅在直接或通过别名来构造 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a> 时发生，并且在子类化时不会被继承。</p>
<p><code>errno</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.errno" title="永久链接至目标"></a></p>
<p>来自于 C 变量 <code>errno</code> 的数字错误码。</p>
<p><code>winerror</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.winerror" title="永久链接至目标"></a></p>
<p>在 Windows 下，此参数将给出原生的 Windows 错误码。 而 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.errno" title="OSError.errno"><code>errno</code></a> 属性将是该原生错误码在 POSIX 平台下的近似转换形式。</p>
<p>在 Windows 下，如果 <em>winerror</em> 构造器参数是一个整数，则 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.errno" title="OSError.errno"><code>errno</code></a> 属性会根据 Windows 错误码来确定，而 <em>errno</em> 参数会被忽略。 在其他平台上，<em>winerror</em> 参数会被忽略，并且 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.winerror" title="OSError.winerror"><code>winerror</code></a> 属性将不存在。</p>
<p><code>strerror</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.strerror" title="永久链接至目标"></a></p>
<p>操作系统所提供的相应错误信息。 它在 POSIX 平台中由 C 函数 <code>perror()</code> 来格式化，在 Windows 中则是由 <code>FormatMessage()</code>。</p>
<p><code>filename</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.filename" title="永久链接至目标"></a></p>
<p><code>filename2</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.filename2" title="永久链接至目标"></a></p>
<p>对于与文件系统路径有关 (例如 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#open" title="open"><code>open()</code></a> 或 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/os.html#os.unlink" title="os.unlink"><code>os.unlink()</code></a>) 的异常，<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.filename" title="OSError.filename"><code>filename</code></a> 是传给函数的文件名。 对于涉及两个文件系统路径的函数 (例如 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/os.html#os.rename" title="os.rename"><code>os.rename()</code></a>)，<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.filename2" title="OSError.filename2"><code>filename2</code></a> 将是传给函数的第二个文件名。</p>
<p>在 3.3 版更改: <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#EnvironmentError" title="EnvironmentError"><code>EnvironmentError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IOError" title="IOError"><code>IOError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#WindowsError" title="WindowsError"><code>WindowsError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/socket.html#socket.error" title="socket.error"><code>socket.error</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/select.html#select.error" title="select.error"><code>select.error</code></a> 与 <code>mmap.error</code> 已被合并到 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a>，构造器可能返回其中一个子类。</p>
<p>在 3.4 版更改: <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError.filename" title="OSError.filename"><code>filename</code></a> 属性现在是传给函数的原始文件名，而不是基于 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-filesystem-encoding-and-error-handler">filesystem encoding and error handler</a> 进行编码或解码之后的名称。 此外，还添加了 <em>filename2</em> 构造器参数和属性。</p>
<p><em>exception</em> <code>OverflowError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OverflowError" title="永久链接至目标"></a></p>
<p>当算术运算的结果大到无法表示时将被引发。 这对整数来说不可能发生（宁可引发 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#MemoryError" title="MemoryError"><code>MemoryError</code></a> 也不会放弃尝试）。 但是出于历史原因，有时也会在整数超出要求范围的情况下引发 OverflowError。 因为在 C 中缺少对浮点异常处理的标准化，大多数浮点运算都不会做检查。</p>
<p><em>exception</em> <code>RecursionError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RecursionError" title="永久链接至目标"></a></p>
<p>此异常派生自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeError" title="RuntimeError"><code>RuntimeError</code></a>。 它会在解释器检测发现超过最大递归深度 (参见 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/sys.html#sys.getrecursionlimit" title="sys.getrecursionlimit"><code>sys.getrecursionlimit()</code></a>) 时被引发。</p>
<p>3.5 新版功能: 在此之前将只引发 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeError" title="RuntimeError"><code>RuntimeError</code></a>。</p>
<p><em>exception</em> <code>ReferenceError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ReferenceError" title="永久链接至目标"></a></p>
<p>此异常将在使用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/weakref.html#weakref.proxy" title="weakref.proxy"><code>weakref.proxy()</code></a> 函数所创建的弱引用来访问该引用的某个已被作为垃圾回收的属性时被引发。 有关弱引用的更多信息请参阅 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code>weakref</code></a> 模块。</p>
<p><em>exception</em> <code>RuntimeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeError" title="永久链接至目标"></a></p>
<p>当检测到一个不归属于任何其他类别的错误时将被引发。 关联的值是一个指明究竟发生了什么问题的字符串。</p>
<p><em>exception</em> <code>StopIteration</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#StopIteration" title="永久链接至目标"></a></p>
<p>由内置函数 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#next" title="next"><code>next()</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-iterator">iterator</a> 的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/stdtypes.html#iterator.__next__" title="iterator.__next__"><code>__next__()</code></a> 方法所引发，用来表示该迭代器不能产生下一项。</p>
<p>该异常对象只有一个属性 <code>value</code>，它在构造该异常时作为参数给出，默认值为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/constants.html#None" title="None"><code>None</code></a>。</p>
<p>当一个 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-generator">generator</a> 或 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-coroutine">coroutine</a> 函数返回时，将引发一个新的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#StopIteration" title="StopIteration"><code>StopIteration</code></a> 实例，函数返回的值将被用作异常构造器的 <code>value</code> 形参。</p>
<p>如果某个生成器代码直接或间接地引发了 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#StopIteration" title="StopIteration"><code>StopIteration</code></a>，它会被转换为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeError" title="RuntimeError"><code>RuntimeError</code></a> (并将 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#StopIteration" title="StopIteration"><code>StopIteration</code></a> 保留为导致新异常的原因)。</p>
<p>在 3.3 版更改: 添加了 <code>value</code> 属性及其被生成器函数用作返回值的功能。</p>
<p>在 3.5 版更改: 引入了通过 <code>from __future__ import generator_stop</code> 来实现 RuntimeError 转换，参见 <a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0479"><strong>PEP 479</strong></a>。</p>
<p>在 3.7 版更改: 默认对所有代码启用 <a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0479"><strong>PEP 479</strong></a>: 在生成器中引发的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#StopIteration" title="StopIteration"><code>StopIteration</code></a> 错误将被转换为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeError" title="RuntimeError"><code>RuntimeError</code></a>。</p>
<p><em>exception</em> <code>StopAsyncIteration</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#StopAsyncIteration" title="永久链接至目标"></a></p>
<p>必须由一个 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/glossary.html#term-asynchronous-iterator">asynchronous iterator</a> 对象的 <code>__anext__()</code> 方法来引发以停止迭代操作。</p>
<p>3.5 新版功能.</p>
<p><em>exception</em> <code>SyntaxError</code>(<em>message</em>, <em>details</em>)<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError" title="永久链接至目标"></a></p>
<p>当解析器遇到语法错误时引发。 这可以发生在 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/simple_stmts.html#import"><code>import</code></a> 语句，对内置函数 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#compile" title="compile"><code>compile()</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#exec" title="exec"><code>exec()</code></a> 或 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#eval" title="eval"><code>eval()</code></a> 的调用，或是读取原始脚本或标准输入（也包括交互模式）的时候。</p>
<p>异常实例的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/stdtypes.html#str" title="str"><code>str()</code></a> 只返回错误消息。 错误详情为一个元组，其成员也可在单独的属性中分别获取。</p>
<p><code>filename</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.filename" title="永久链接至目标"></a></p>
<p>发生语法错误所在文件的名称。</p>
<p><code>lineno</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.lineno" title="永久链接至目标"></a></p>
<p>发生错误所在文件中的行号。 行号索引从 1 开始：文件中首行的 <code>lineno</code> 为 1。</p>
<p><code>offset</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.offset" title="永久链接至目标"></a></p>
<p>发生错误所在文件中的列号。 列号索引从 1 开始：行中首个字符的 <code>offset</code> 为 1。</p>
<p><code>text</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.text" title="永久链接至目标"></a></p>
<p>错误所涉及的源代码文本。</p>
<p><code>end_lineno</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.end_lineno" title="永久链接至目标"></a></p>
<p>发生的错误在文件中的末尾行号。 这个索引是从 1 开始的：文件中首行的 <code>lineno</code> 为 1。</p>
<p><code>end_offset</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.end_offset" title="永久链接至目标"></a></p>
<p>发生的错误在文件中的末尾列号。 这个索引是从 1 开始：行中首个字符的 <code>offset</code> 为 1。</p>
<p>对于 f-字符串字段中的错误，消息会带有 “f-string: “ 前缀并且其位置是基于替换表达式构建的文本中的位置。 例如，编译 f’Bad {a b} field’ 将产生这样的 args 属性: (‘f-string: …’, (‘’, 1, 2, ‘(a b)n’, 1, 5))。</p>
<p>在 3.10 版更改: 增加了 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.end_lineno" title="SyntaxError.end_lineno"><code>end_lineno</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError.end_offset" title="SyntaxError.end_offset"><code>end_offset</code></a> 属性。</p>
<p><em>exception</em> <code>IndentationError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IndentationError" title="永久链接至目标"></a></p>
<p>与不正确的缩进相关的语法错误的基类。 这是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxError" title="SyntaxError"><code>SyntaxError</code></a> 的一个子类。</p>
<p><em>exception</em> <code>TabError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#TabError" title="永久链接至目标"></a></p>
<p>当缩进包含对制表符和空格符不一致的使用时将被引发。 这是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IndentationError" title="IndentationError"><code>IndentationError</code></a> 的一个子类。</p>
<p><em>exception</em> <code>SystemError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SystemError" title="永久链接至目标"></a></p>
<p>当解释器发现内部错误，但情况看起来尚未严重到要放弃所有希望时将被引发。 关联的值是一个指明发生了什么问题的字符串（表示为低层级的符号）。</p>
<p>你应当将此问题报告给你所用 Python 解释器的作者或维护人员。 请确认报告 Python 解释器的版本号 (<code>sys.version</code>; 它也会在交互式 Python 会话开始时被打印出来)，具体的错误消息（异常所关联的值）以及可能触发该错误的程序源码。</p>
<p><em>exception</em> <code>SystemExit</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SystemExit" title="永久链接至目标"></a></p>
<p>此异常由 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/sys.html#sys.exit" title="sys.exit"><code>sys.exit()</code></a> 函数引发。 它继承自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BaseException" title="BaseException"><code>BaseException</code></a> 而不是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="Exception"><code>Exception</code></a> 以确保不会被处理 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Exception" title="Exception"><code>Exception</code></a> 的代码意外捕获。 这允许此异常正确地向上传播并导致解释器退出。 如果它未被处理，则 Python 解释器就将退出；不会打印任何栈回溯信息。 构造器接受的可选参数与传递给 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/sys.html#sys.exit" title="sys.exit"><code>sys.exit()</code></a> 的相同。 如果该值为一个整数，则它指明系统退出状态码（会传递给 C 的 <code>exit()</code> 函数）；如果该值为 <code>None</code>，则退出状态码为零；如果该值为其他类型（例如字符串），则会打印对象的值并将退出状态码设为一。</p>
<p>对 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/sys.html#sys.exit" title="sys.exit"><code>sys.exit()</code></a> 的调用会被转换为一个异常以便能执行清理处理程序 (<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#try"><code>try</code></a> 语句的 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/reference/compound_stmts.html#finally"><code>finally</code></a> 子句)，并且使得调试器可以执行一段脚本而不必冒失去控制的风险。 如果绝对确实地需要立即退出（例如在调用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/os.html#os.fork" title="os.fork"><code>os.fork()</code></a> 之后的子进程中）则可使用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/os.html#os._exit" title="os._exit"><code>os._exit()</code></a>.</p>
<p><code>code</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SystemExit.code" title="永久链接至目标"></a></p>
<p>传给构造器的退出状态码或错误信息（默认为 <code>None</code>。）</p>
<p><em>exception</em> <code>TypeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#TypeError" title="永久链接至目标"></a></p>
<p>当一个操作或函数被应用于类型不适当的对象时将被引发。 关联的值是一个字符串，给出有关类型不匹配的详情。</p>
<p>此异常可以由用户代码引发，以表明尝试对某个对象进行的操作不受支持也不应当受支持。 如果某个对象应当支持给定的操作但尚未提供相应的实现，所要引发的适当异常应为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#NotImplementedError" title="NotImplementedError"><code>NotImplementedError</code></a>。</p>
<p>传入参数的类型错误 (例如在要求 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#int" title="int"><code>int</code></a> 时却传入了 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/stdtypes.html#list" title="list"><code>list</code></a>) 应当导致 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#TypeError" title="TypeError"><code>TypeError</code></a>，但传入参数的值错误 (例如传入要求范围之外的数值) 则应当导致 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ValueError" title="ValueError"><code>ValueError</code></a>。</p>
<p><em>exception</em> <code>UnboundLocalError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnboundLocalError" title="永久链接至目标"></a></p>
<p>当在函数或方法中对某个局部变量进行引用，但该变量并未绑定任何值时将被引发。 此异常是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#NameError" title="NameError"><code>NameError</code></a> 的一个子类。</p>
<p><em>exception</em> <code>UnicodeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError" title="永久链接至目标"></a></p>
<p>当发生与 Unicode 相关的编码或解码错误时将被引发。 此异常是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ValueError" title="ValueError"><code>ValueError</code></a> 的一个子类。</p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError" title="UnicodeError"><code>UnicodeError</code></a> 具有一些描述编码或解码错误的属性。 例如 <code>err.object[err.start:err.end]</code> 会给出导致编解码器失败的特定无效输入。</p>
<p><code>encoding</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError.encoding" title="永久链接至目标"></a></p>
<p>引发错误的编码名称。</p>
<p><code>reason</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError.reason" title="永久链接至目标"></a></p>
<p>描述特定编解码器错误的字符串。</p>
<p><code>object</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError.object" title="永久链接至目标"></a></p>
<p>编解码器试图要编码或解码的对象。</p>
<p><code>start</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError.start" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#object" title="object"><code>object</code></a> 中无效数据的开始位置索引。</p>
<p><code>end</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError.end" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/functions.html#object" title="object"><code>object</code></a> 中无效数据的末尾位置索引（不含）。</p>
<p><em>exception</em> <code>UnicodeEncodeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeEncodeError" title="永久链接至目标"></a></p>
<p>当在编码过程中发生与 Unicode 相关的错误时将被引发。 此异常是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError" title="UnicodeError"><code>UnicodeError</code></a> 的一个子类。</p>
<p><em>exception</em> <code>UnicodeDecodeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeDecodeError" title="永久链接至目标"></a></p>
<p>当在解码过程中发生与 Unicode 相关的错误时将被引发。 此异常是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError" title="UnicodeError"><code>UnicodeError</code></a> 的一个子类。</p>
<p><em>exception</em> <code>UnicodeTranslateError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeTranslateError" title="永久链接至目标"></a></p>
<p>在转写过程中发生与 Unicode 相关的错误时将被引发。 此异常是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeError" title="UnicodeError"><code>UnicodeError</code></a> 的一个子类。</p>
<p><em>exception</em> <code>ValueError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ValueError" title="永久链接至目标"></a></p>
<p>当操作或函数接收到具有正确类型但值不适合的参数，并且情况不能用更精确的异常例如 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IndexError" title="IndexError"><code>IndexError</code></a> 来描述时将被引发。</p>
<p><em>exception</em> <code>ZeroDivisionError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ZeroDivisionError" title="永久链接至目标"></a></p>
<p>当除法或取余运算的第二个参数为零时将被引发。 关联的值是一个字符串，指明操作数和运算的类型。</p>
<p>下列异常被保留以与之前的版本相兼容；从 Python 3.3 开始，它们都是 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a> 的别名。</p>
<p><em>exception</em> <code>EnvironmentError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#EnvironmentError" title="永久链接至目标"></a></p>
<p><em>exception</em> <code>IOError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IOError" title="永久链接至目标"></a></p>
<p><em>exception</em> <code>WindowsError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#WindowsError" title="永久链接至目标"></a></p>
<p>限在 Windows 中可用。</p>
<h3 id="OS-异常"><a href="#OS-异常" class="headerlink" title="OS 异常"></a>OS 异常</h3><p>下列异常均为 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a> 的子类，它们将根据系统错误代码被引发。</p>
<p><em>exception</em> <code>BlockingIOError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BlockingIOError" title="永久链接至目标"></a></p>
<p>当一个操作将会在设置为非阻塞操作的对象（例如套接字）上发生阻塞时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EAGAIN" title="errno.EAGAIN"><code>EAGAIN</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EALREADY" title="errno.EALREADY"><code>EALREADY</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EWOULDBLOCK" title="errno.EWOULDBLOCK"><code>EWOULDBLOCK</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EINPROGRESS" title="errno.EINPROGRESS"><code>EINPROGRESS</code></a>。</p>
<p>除了 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a> 已有的属性，<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BlockingIOError" title="BlockingIOError"><code>BlockingIOError</code></a> 还有一个额外属性：</p>
<p><code>characters_written</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BlockingIOError.characters_written" title="永久链接至目标"></a></p>
<p>一个整数，表示在被阻塞前已写入到流的字符数。 当使用来自 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/io.html#module-io" title="io: Core tools for working with streams."><code>io</code></a> 模块的带缓冲 I&#x2F;O 类时此属性可用。</p>
<p><em>exception</em> <code>ChildProcessError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ChildProcessError" title="永久链接至目标"></a></p>
<p>当一个子进程上的操作失败时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ECHILD" title="errno.ECHILD"><code>ECHILD</code></a>。</p>
<p><em>exception</em> <code>ConnectionError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionError" title="永久链接至目标"></a></p>
<p>与连接相关问题的基类。</p>
<p>其子类有 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BrokenPipeError" title="BrokenPipeError"><code>BrokenPipeError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionAbortedError" title="ConnectionAbortedError"><code>ConnectionAbortedError</code></a>, <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionRefusedError" title="ConnectionRefusedError"><code>ConnectionRefusedError</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionResetError" title="ConnectionResetError"><code>ConnectionResetError</code></a>。</p>
<p><em>exception</em> <code>BrokenPipeError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BrokenPipeError" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionError" title="ConnectionError"><code>ConnectionError</code></a> 的子类，当试图写入一个管道而该管道的另一端已关闭，或者试图写入一个套接字而该套接字已关闭写入时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EPIPE" title="errno.EPIPE"><code>EPIPE</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ESHUTDOWN" title="errno.ESHUTDOWN"><code>ESHUTDOWN</code></a>。</p>
<p><em>exception</em> <code>ConnectionAbortedError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionAbortedError" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionError" title="ConnectionError"><code>ConnectionError</code></a> 的子类，当一个连接尝试被对端中止时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ECONNABORTED" title="errno.ECONNABORTED"><code>ECONNABORTED</code></a>。</p>
<p><em>exception</em> <code>ConnectionRefusedError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionRefusedError" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionError" title="ConnectionError"><code>ConnectionError</code></a> 的子类，当一个连接尝试被对端拒绝时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ECONNREFUSED" title="errno.ECONNREFUSED"><code>ECONNREFUSED</code></a>。</p>
<p><em>exception</em> <code>ConnectionResetError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionResetError" title="永久链接至目标"></a></p>
<p><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ConnectionError" title="ConnectionError"><code>ConnectionError</code></a> 的子类，当一个连接尝试被对端重置时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ECONNRESET" title="errno.ECONNRESET"><code>ECONNRESET</code></a>。</p>
<p><em>exception</em> <code>FileExistsError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#FileExistsError" title="永久链接至目标"></a></p>
<p>当试图创建一个已存在的文件或目录时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EEXIST" title="errno.EEXIST"><code>EEXIST</code></a>。</p>
<p><em>exception</em> <code>FileNotFoundError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#FileNotFoundError" title="永久链接至目标"></a></p>
<p>将所请求的文件或目录不存在时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ENOENT" title="errno.ENOENT"><code>ENOENT</code></a>。</p>
<p><em>exception</em> <code>InterruptedError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#InterruptedError" title="永久链接至目标"></a></p>
<p>当系统调用被输入信号中断时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EINTR" title="errno.EINTR"><code>EINTR</code></a>。</p>
<p>在 3.5 版更改: 当系统调用被某个信号中断时，Python 现在会重试系统调用，除非该信号的处理程序引发了其它异常 (原理参见 <a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0475"><strong>PEP 475</strong></a>) 而不是引发 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#InterruptedError" title="InterruptedError"><code>InterruptedError</code></a>。</p>
<p><em>exception</em> <code>IsADirectoryError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#IsADirectoryError" title="永久链接至目标"></a></p>
<p>当请求对一个目录执行文件操作 (例如 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/os.html#os.remove" title="os.remove"><code>os.remove()</code></a>) 时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EISDIR" title="errno.EISDIR"><code>EISDIR</code></a>。</p>
<p><em>exception</em> <code>NotADirectoryError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#NotADirectoryError" title="永久链接至目标"></a></p>
<p>当请求对一个非目录执行目录操作 (例如 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/os.html#os.listdir" title="os.listdir"><code>os.listdir()</code></a>) 时将被引发。 在大多数 POSIX 平台上，它还可能在某个操作试图将一个非目录作为目录打开或遍历时被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ENOTDIR" title="errno.ENOTDIR"><code>ENOTDIR</code></a>。</p>
<p><em>exception</em> <code>PermissionError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#PermissionError" title="永久链接至目标"></a></p>
<p>当在没有足够访问权限的情况下试图执行某个操作时将被引发 —— 例如文件系统权限。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EACCES" title="errno.EACCES"><code>EACCES</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.EPERM" title="errno.EPERM"><code>EPERM</code></a>。</p>
<p><em>exception</em> <code>ProcessLookupError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ProcessLookupError" title="永久链接至目标"></a></p>
<p>当给定的进程不存在时将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ESRCH" title="errno.ESRCH"><code>ESRCH</code></a>。</p>
<p><em>exception</em> <code>TimeoutError</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#TimeoutError" title="永久链接至目标"></a></p>
<p>当一个系统函数在系统层级发生超时的情况下将被引发。 对应于 <code>errno</code> <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/errno.html#errno.ETIMEDOUT" title="errno.ETIMEDOUT"><code>ETIMEDOUT</code></a>。</p>
<p>3.3 新版功能: 添加了以上所有 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#OSError" title="OSError"><code>OSError</code></a> 的子类。</p>
<p>参见</p>
<p> </p>
<p><a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-3151"><strong>PEP 3151</strong></a> - 重写 OS 和 IO 异常的层次结构</p>
<h2 id="警告"><a href="#警告" class="headerlink" title="警告"></a>警告</h2><p>下列异常被用作警告类别；请参阅 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/warnings.html#warning-categories">警告类别</a> 文档了解详情。</p>
<p><em>exception</em> <code>Warning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#Warning" title="永久链接至目标"></a></p>
<p>警告类别的基类。</p>
<p><em>exception</em> <code>UserWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UserWarning" title="永久链接至目标"></a></p>
<p>用户代码所产生警告的基类。</p>
<p><em>exception</em> <code>DeprecationWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#DeprecationWarning" title="永久链接至目标"></a></p>
<p>如果所发出的警告是针对其他 Python 开发者的，则以此作为与已弃用特性相关警告的基类。</p>
<p>会被默认警告过滤器忽略，在 <code>__main__</code> 模块中的情况除外 (<a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0565"><strong>PEP 565</strong></a>)。 启用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/devmode.html#devmode">Python 开发模式</a> 时会显示此警告。</p>
<p>这个弃用政策是在 <a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0387"><strong>PEP 387</strong></a> 中描述的。</p>
<p><em>exception</em> <code>PendingDeprecationWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#PendingDeprecationWarning" title="永久链接至目标"></a></p>
<p>对于已过时并预计在未来弃用，但目前尚未弃用的特性相关警告的基类。</p>
<p>这个类很少被使用，因为针对未来可能的弃用发出警告的做法并不常见，而针对当前已有的弃用则推荐使用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#DeprecationWarning" title="DeprecationWarning"><code>DeprecationWarning</code></a>。</p>
<p>会被默认警告过滤器忽略。 启用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/devmode.html#devmode">Python 开发模式</a> 时会显示此警告。</p>
<p>这个弃用政策是在 <a target="_blank" rel="noopener" href="https://www.python.org/dev/peps/pep-0387"><strong>PEP 387</strong></a> 中描述的。</p>
<p><em>exception</em> <code>SyntaxWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#SyntaxWarning" title="永久链接至目标"></a></p>
<p>与模糊的语法相关的警告的基类。</p>
<p><em>exception</em> <code>RuntimeWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#RuntimeWarning" title="永久链接至目标"></a></p>
<p>与模糊的运行时行为相关的警告的基类。</p>
<p><em>exception</em> <code>FutureWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#FutureWarning" title="永久链接至目标"></a></p>
<p>如果所发出的警告是针对以 Python 所编写应用的最终用户的，则以此作为与已弃用特性相关警告的基类。</p>
<p><em>exception</em> <code>ImportWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ImportWarning" title="永久链接至目标"></a></p>
<p>与在模块导入中可能的错误相关的警告的基类。</p>
<p>会被默认警告过滤器忽略。 启用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/devmode.html#devmode">Python 开发模式</a> 时会显示此警告。</p>
<p><em>exception</em> <code>UnicodeWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#UnicodeWarning" title="永久链接至目标"></a></p>
<p>与 Unicode 相关的警告的基类。</p>
<p><em>exception</em> <code>EncodingWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#EncodingWarning" title="永久链接至目标"></a></p>
<p>与编码格式相关的警告的基类。</p>
<p>请参阅 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/io.html#io-encoding-warning">选择性的 EncodingWarning</a> 来了解详情。</p>
<p>3.10 新版功能.</p>
<p><em>exception</em> <code>BytesWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#BytesWarning" title="永久链接至目标"></a></p>
<p>与 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/stdtypes.html#bytes" title="bytes"><code>bytes</code></a> 和 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/stdtypes.html#bytearray" title="bytearray"><code>bytearray</code></a> 相关的警告的基类。</p>
<p><em>exception</em> <code>ResourceWarning</code><a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/exceptions.html#ResourceWarning" title="永久链接至目标"></a></p>
<p>资源使用相关警告的基类。</p>
<p>会被默认警告过滤器忽略。 启用 <a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3.10/library/devmode.html#devmode">Python 开发模式</a> 时会显示此警告。</p>
<p>3.2 新版功能.</p>
<h2 id="异常层次结构"><a href="#异常层次结构" class="headerlink" title="异常层次结构"></a>异常层次结构</h2><p>内置异常的类层级结构如下：</p>
<p>BaseException<br> +– SystemExit<br> +– KeyboardInterrupt<br> +– GeneratorExit<br> +– Exception<br>      +– StopIteration<br>      +– StopAsyncIteration<br>      +– ArithmeticError<br>      |    +– FloatingPointError<br>      |    +– OverflowError<br>      |    +– ZeroDivisionError<br>      +– AssertionError<br>      +– AttributeError<br>      +– BufferError<br>      +– EOFError<br>      +– ImportError<br>      |    +– ModuleNotFoundError<br>      +– LookupError<br>      |    +– IndexError<br>      |    +– KeyError<br>      +– MemoryError<br>      +– NameError<br>      |    +– UnboundLocalError<br>      +– OSError<br>      |    +– BlockingIOError<br>      |    +– ChildProcessError<br>      |    +– ConnectionError<br>      |    |    +– BrokenPipeError<br>      |    |    +– ConnectionAbortedError<br>      |    |    +– ConnectionRefusedError<br>      |    |    +– ConnectionResetError<br>      |    +– FileExistsError<br>      |    +– FileNotFoundError<br>      |    +– InterruptedError<br>      |    +– IsADirectoryError<br>      |    +– NotADirectoryError<br>      |    +– PermissionError<br>      |    +– ProcessLookupError<br>      |    +– TimeoutError<br>      +– ReferenceError<br>      +– RuntimeError<br>      |    +– NotImplementedError<br>      |    +– RecursionError<br>      +– SyntaxError<br>      |    +– IndentationError<br>      |         +– TabError<br>      +– SystemError<br>      +– TypeError<br>      +– ValueError<br>      |    +– UnicodeError<br>      |         +– UnicodeDecodeError<br>      |         +– UnicodeEncodeError<br>      |         +– UnicodeTranslateError<br>      +– Warning<br>           +– DeprecationWarning<br>           +– PendingDeprecationWarning<br>           +– RuntimeWarning<br>           +– SyntaxWarning<br>           +– UserWarning<br>           +– FutureWarning<br>           +– ImportWarning<br>           +– UnicodeWarning<br>           +– BytesWarning<br>           +– EncodingWarning<br>           +– ResourceWarning</p>
</article><div class="post-copyright"><div class="post-copyright__author"><span class="post-copyright-meta"><i class="fas fa-circle-user fa-fw"></i>文章作者: </span><span class="post-copyright-info"><a href="http://Asuka23333.github.io">Asuka</a></span></div><div class="post-copyright__type"><span class="post-copyright-meta"><i class="fas fa-square-arrow-up-right fa-fw"></i>文章链接: </span><span class="post-copyright-info"><a href="http://asuka23333.github.io/2024/01/08/Python/%E5%86%85%E7%BD%AE%E5%BC%82%E5%B8%B8/">http://asuka23333.github.io/2024/01/08/Python/内置异常/</a></span></div><div class="post-copyright__notice"><span class="post-copyright-meta"><i class="fas fa-circle-exclamation fa-fw"></i>版权声明: </span><span class="post-copyright-info">本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a> 许可协议。转载请注明来自 <a href="http://Asuka23333.github.io" target="_blank">知识库</a>！</span></div></div><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Python-Python%E6%A0%87%E5%87%86%E5%BA%93-%E5%BC%82%E5%B8%B8%E4%B8%8A%E4%B8%8B%E6%96%87-%E4%BB%8E%E5%86%85%E7%BD%AE%E5%BC%82%E5%B8%B8%E7%BB%A7%E6%89%BF-%E5%9F%BA%E7%B1%BB-%E5%85%B7%E4%BD%93%E5%BC%82%E5%B8%B8-%E8%AD%A6%E5%91%8A-%E5%BC%82%E5%B8%B8%E5%B1%82%E6%AC%A1%E7%BB%93%E6%9E%84/">Python Python标准库 异常上下文 从内置异常继承 基类 具体异常 警告 异常层次结构</a></div><div class="post_share"><div class="social-share" data-image="/img/net_icon.png" data-sites="wechat,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc@1.1.3/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc@1.1.3/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><div class="prev-post pull-left"><a href="/2024/01/08/Python/%E5%86%85%E7%BD%AE%E5%B8%B8%E9%87%8F/" title=""><div class="cover" style="background: var(--default-bg-color)"></div><div class="pagination-info"><div class="label">上一篇</div><div class="prev_info"></div></div></a></div><div class="next-post pull-right"><a href="/2024/01/08/Python/%E5%86%85%E7%BD%AE%E5%87%BD%E6%95%B0/" title=""><div class="cover" style="background: var(--default-bg-color)"></div><div class="pagination-info"><div class="label">下一篇</div><div class="next_info"></div></div></a></div></nav><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="waline-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">个人知识库, 用于记录学习笔记, 有兴趣可以一起交流</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%BC%82%E5%B8%B8%E4%B8%8A%E4%B8%8B%E6%96%87"><span class="toc-number">1.</span> <span class="toc-text">异常上下文</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E4%BB%8E%E5%86%85%E7%BD%AE%E5%BC%82%E5%B8%B8%E7%BB%A7%E6%89%BF"><span class="toc-number">2.</span> <span class="toc-text">从内置异常继承</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%9F%BA%E7%B1%BB"><span class="toc-number">3.</span> <span class="toc-text">基类</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%85%B7%E4%BD%93%E5%BC%82%E5%B8%B8"><span class="toc-number">4.</span> <span class="toc-text">具体异常</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#OS-%E5%BC%82%E5%B8%B8"><span class="toc-number">4.1.</span> <span class="toc-text">OS 异常</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%AD%A6%E5%91%8A"><span class="toc-number">5.</span> <span class="toc-text">警告</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%BC%82%E5%B8%B8%E5%B1%82%E6%AC%A1%E7%BB%93%E6%9E%84"><span class="toc-number">6.</span> <span class="toc-text">异常层次结构</span></a></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/01/08/Python/%E9%9B%86%E5%90%88/" title="无题">无题</a><time datetime="2024-01-08T07:01:50.225Z" title="发表于 2024-01-08 15:01:50">2024-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/01/08/Python/%E8%BF%90%E7%AE%97%E7%AC%A6/" title="无题">无题</a><time datetime="2024-01-08T07:01:50.224Z" title="发表于 2024-01-08 15:01:50">2024-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/01/08/Python/%E8%8E%B7%E5%8F%96%E9%94%AE%E7%9B%98%E8%BE%93%E5%85%A5/" title="无题">无题</a><time datetime="2024-01-08T07:01:50.223Z" title="发表于 2024-01-08 15:01:50">2024-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/01/08/Python/%E8%AF%AD%E5%8F%A5continue%E5%92%8Cbreak/" title="无题">无题</a><time datetime="2024-01-08T07:01:50.223Z" title="发表于 2024-01-08 15:01:50">2024-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/01/08/Python/%E7%BC%96%E8%BE%91%E5%99%A8PyCharm%E5%BF%AB%E6%8D%B7%E9%94%AE/" title="无题">无题</a><time datetime="2024-01-08T07:01:50.222Z" title="发表于 2024-01-08 15:01:50">2024-01-08</time></div></div></div></div></div></div></main><footer id="footer"><div id="footer-wrap"><div class="copyright">&copy;2024 By Asuka</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="浅色和深色模式转换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><button id="chat-btn" type="button" title="聊天"><i class="fas fa-sms"></i></button><a id="to_comment" href="#post-comment" title="直达评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js?v=4.12.0"></script><script src="/js/main.js?v=4.12.0"></script><script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.32/dist/fancybox/fancybox.umd.min.js"></script><div class="js-pjax"><script>(() => {
  const initWaline = () => {
    const waline = Waline.init(Object.assign({
      el: '#waline-wrap',
      serverURL: 'https://waline-nu-two.vercel.app/',
      pageview: false,
      dark: 'html[data-theme="dark"]',
      path: window.location.pathname,
      comment: false,
    }, {"requiredMeta":["nick"],"locale":{"placeholder":"请勿发表政治相关言论!!! 或是抱怨人生诸事不满!!! 仅以学习交流为目的"}}))

    const destroyWaline = () => {
      waline.destroy()
    }

    btf.addGlobalFn('pjax', destroyWaline, 'destroyWaline')

  }

  const loadWaline = async () => {
    if (typeof Waline === 'object') initWaline()
    else {
      await getCSS('https://cdn.jsdelivr.net/npm/@waline/client@2.15.8/dist/waline.min.css')
      await getScript('https://cdn.jsdelivr.net/npm/@waline/client@2.15.8/dist/waline.min.js')
      initWaline()
    }
  }

  if ('Waline' === 'Waline' || !false) {
    if (false) btf.loadComment(document.getElementById('waline-wrap'),loadWaline)
    else setTimeout(loadWaline, 0)
  } else {
    window.loadOtherComment = loadWaline
  }
})()</script></div><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="is-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据库加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js?v=4.12.0"></script></div></div></body></html>